// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnVmrW98rLqEES0H6lq8I-9Me_VKVdB38',
    appId: '1:1042254612751:android:0d7993439fb6d2c484d67a',
    messagingSenderId: '1042254612751',
    projectId: 'flutter-test-c03e4',
    databaseURL: 'https://flutter-test-c03e4-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-c03e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU5Wmffb9JMBrF2BLhdg3_CBEwJ5KFKf4',
    appId: '1:1042254612751:ios:bde438e936c1cc0084d67a',
    messagingSenderId: '1042254612751',
    projectId: 'flutter-test-c03e4',
    databaseURL: 'https://flutter-test-c03e4-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-c03e4.appspot.com',
    iosClientId: '1042254612751-65kh8hpvtn0alfpcriglj6a7uueej9ql.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );
}
